In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [5]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["director"] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not Availabe')
df['country'] = df['country'].fillna('Unknown')
df['date_added'] = df['date_added'].ffill()
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])
df['duration'] = df['duration'].fillna('0 min')

In [8]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      8807 non-null   str
 4   cast          8807 non-null   str
 5   country       8807 non-null   str
 6   date_added    8807 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8807 non-null   str
 9   duration      8807 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [12]:
df['date_added'].sample(20)

6095         May 27, 2019
5704     December 1, 2016
1685    November 17, 2020
2295         July 3, 2020
7251        March 1, 2018
3364     October 29, 2019
4778        July 10, 2018
8615         July 1, 2018
1091        April 8, 2021
2762       March 28, 2020
970        April 27, 2021
1092        April 7, 2021
4327     December 2, 2018
4143     February 1, 2019
4519     October 12, 2018
7078         July 1, 2019
394         July 23, 2021
3794         May 27, 2019
6575    November 21, 2018
8078       August 8, 2019
Name: date_added, dtype: str

In [13]:
df['date_added'] = df['date_added'].str.strip()

In [14]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [15]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [16]:
df.sample(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8179,s8180,Movie,The Adderall Diaries,Pamela Romanowsky,"James Franco, Ed Harris, Amber Heard, Jim Parr...",United States,2018-07-15,2015,R,87 min,"Dramas, Thrillers",Author Stephen Elliott has a problem separatin...
8211,s8212,Movie,The Black Room,Rolfe Kanefsky,"Natasha Henstridge, Lukas Hassel, Lin Shaye, D...",United States,2017-08-07,2016,TV-MA,95 min,Horror Movies,A couple's new dream home morphs into a nightm...
3610,s3611,TV Show,Let’s Eat,Unknown,"Lee Soo-kyung, Yoon Du-jun, Yoon So-hui, Shim ...",South Korea,2019-08-08,2013,TV-PG,1 Season,"International TV Shows, Korean TV Shows, Roman...","With the help of her neighbors, a divorced wom..."
7831,s7832,Movie,Rampant,Kim Sung-hoon,"Hyun Bin, Jang Dong-gun, Jo Woo-jin, Jeong Man...",South Korea,2019-05-26,2018,TV-MA,122 min,"Action & Adventure, Horror Movies, Internation...",When Prince Lee Cheong returns to Joseon after...
5025,s5026,Movie,Veronica,Paco Plaza,"Sandra Escacena, Claudia Placer, Bruna Gonzále...",Spain,2018-02-25,2017,TV-MA,105 min,"Horror Movies, International Movies, Thrillers","In 1991 Madrid, after holding a séance at scho..."
8684,s8685,TV Show,Vroomiz,Unknown,"Joon-seok Song, Jeong-hwa Yang, Sang-hyun Um, ...",South Korea,2017-08-01,2016,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows","For these half-car, half-animal friends, each ..."
8209,s8210,TV Show,The Big Catch,Unknown,Ben Fogle,United Kingdom,2019-02-01,2015,TV-PG,1 Season,"British TV Shows, Reality TV","In a global competition, eight fishing enthusi..."
6518,s6519,Movie,Come and Find Me,Zack Whedon,"Aaron Paul, Annabelle Wallis, Garret Dillahunt...","Canada, United States, United Kingdom",2019-09-18,2016,R,112 min,"Dramas, Thrillers","When his photographer girlfriend vanishes, an ..."
6277,s6278,Movie,Beiimaan Love,Rajeev Chaudhari,"Sunny Leone, Rajneesh Duggal, Rajeev Verma, Da...",India,2017-11-01,2016,TV-MA,115 min,"Dramas, International Movies, Romantic Movies",After having her heart broken by a man who sed...
2811,s2812,Movie,Digs & Discoveries: All Track's Lead to Rome,Joey So,"Joseph May, Anna Francolini, Antonio Magro, Mo...",Unknown,2020-03-15,2019,TV-Y,23 min,Children & Family Movies,After being introduced to Italy's ancient hist...
1314,s1315,TV Show,Chappelle's Show,Unknown,Dave Chappelle,United States,2021-02-12,2005,TV-MA,2 Seasons,TV Comedies,The brilliant Dave Chappelle performs blisteri...
6646,s6647,TV Show,Dramaworld,Unknown,"Liv Hewson, Sean Dulake, Justin Chon, Noo-Ri B...","United States, South Korea, China",2016-05-23,2016,TV-14,1 Season,"Romantic TV Shows, TV Comedies, TV Dramas",A huge fan of a Korean TV drama is transported...
3527,s3528,TV Show,"The Mind, Explained",Unknown,Emma Stone,United States,2019-09-12,2019,TV-14,1 Season,"Docuseries, Science & Nature TV",Ever wonder what's happening inside your head?...
796,s797,Movie,Hostel: Part III,Scott Spiegel,"Kip Pardue, Brian Hallisay, John Hensley, Sara...",United States,2021-06-02,2011,R,88 min,"Cult Movies, Horror Movies",In this installment in the popular horror fran...
1227,s1228,TV Show,Bombay Begums,Unknown,"Pooja Bhatt, Shahana Goswami, Amruta Subhash, ...",India,2021-03-08,2021,TV-MA,1 Season,"International TV Shows, TV Dramas","From boardrooms to society's margins, five amb..."
1107,s1108,Movie,God Calling,BB Sasore,"Zainab Balogun, Karibi Fubara, Diana Egwuatu, ...",Nigeria,2021-04-02,2018,TV-MA,120 min,"Dramas, Faith & Spirituality, International Mo...",The loss of a child plunges Sade into a suicid...
5552,s5553,Movie,Toro,Kike Maíllo,"Mario Casas, Luis Tosar, José Sacristán, Claud...",Spain,2017-04-01,2016,TV-MA,106 min,"Dramas, International Movies, Thrillers",Ex-con Toro's brother and former partner in cr...
3487,s3488,Movie,The Grandmaster,Wong Kar Wai,"Tony Leung Chiu-wai, Zhang Ziyi, Chang Chen, X...","Hong Kong, China",2019-09-26,2013,PG-13,108 min,"Action & Adventure, Dramas, International Movies","As the Japanese invasion looms, Chinese kung f..."
5462,s5463,Movie,Qila,Umesh Mehra,"Dilip Kumar, Mukul Dev, Rekha, Mamta Kulkarni,...",India,2017-06-01,1998,TV-14,161 min,"Dramas, International Movies","When an abusive landowner is murdered, his twi..."
5185,s5186,TV Show,Alias Grace,Unknown,"Sarah Gadon, Edward Holcroft, Paul Gross, Anna...",Canada,2017-11-03,2017,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In 19th-century Canada, a psychiatrist weighs ..."

In [17]:
df['duration'].unique()

<StringArray>
[   '90 min', '2 Seasons',  '1 Season',    '91 min',   '125 min', '9 Seasons',
   '104 min',   '127 min', '4 Seasons',    '67 min',
 ...
    '43 min',   '200 min',   '196 min',   '167 min',   '178 min',   '228 min',
    '18 min',   '205 min',   '201 min',   '191 min']
Length: 221, dtype: str

In [18]:
df['Duration_value'] = df['duration'].str.split().str[0]

In [19]:
df['Duration_type'] = df['duration'].str.split().str[1]

In [20]:
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Duration_value,Duration_type
3586,s3587,Movie,The Little Switzerland,Kepa Sojo,"Jon Plazaola, Maggie Civantos, Ingrid García J...",Spain,2019-08-16,2019,TV-MA,86 min,"Comedies, International Movies",The discovery of the tomb of William Tell’s so...,86,min
1293,s1294,TV Show,Pitta Kathalu,"Tharun Bhascker Dhaassyam, B. V. Nandini Reddy...","Manchu Lakshmi, Saanve Megghana, Naveen Kumar,...",India,2021-02-19,2021,TV-MA,1 Season,"International TV Shows, TV Dramas","From secrets and lies to jealousy and control,...",1,Season
5194,s5195,TV Show,The Truth,Unknown,"Tay Ping Hui, Joanne Peh, Shaun Chen, Rebecca ...",Unknown,2017-11-01,2008,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Act...",A devious businessman covets his partner's pri...,1,Season
2394,s2395,TV Show,Dating Around,Unknown,Not Availabe,Unknown,2020-06-12,2020,TV-MA,2 Seasons,"Reality TV, Romantic TV Shows","In each episode of flirtations and fails, one ...",2,Seasons
518,s519,Movie,Har Kisse Ke Hisse: Kaamyaab,Hardik Mehta,"Sanjay Mishra, Deepak Dobriyal, Sarika Singh, ...",India,2021-07-06,2020,TV-14,105 min,"Dramas, International Movies","After a career of thankless credits, a retired...",105,min
3890,s3891,Movie,Njan Prakashan,Sathyan Anthikad,"Fahadh Faasil, Sreenivasan, Nikhila Vimal, Dev...",India,2019-04-26,2018,TV-PG,125 min,"Comedies, Dramas, International Movies","Yearning for a lavish life abroad, an entitled...",125,min
8740,s8741,TV Show,Wild Alaska,Unknown,Dougray Scott,United Kingdom,2017-03-31,2015,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV",The natural bounty of Alaska sustains its dive...,1,Season
565,s566,TV Show,Bureau of Magical Things,Unknown,"Kimie Tsukakoshi, Elizabeth Cullen, Mia Milnes...","Australia, Germany",2021-07-01,2020,TV-G,1 Season,"International TV Shows, Kids' TV, TV Mysteries",When a teen accidentally discovers an enchante...,1,Season
1412,s1413,Movie,Wish You,Sung Do-jun,"Kang In-soo, Lee Sang, Soo-bin",South Korea,2021-01-15,2021,TV-PG,102 min,"Dramas, International Movies, LGBTQ Movies","Singing and dreaming together, a talented sing...",102,min
1396,s1397,Movie,Homefront,Gary Fleder,"Jason Statham, James Franco, Izabela Vidovic, ...",United States,2021-01-18,2013,R,100 min,Action & Adventure,"When an ex-DEA agent is widowed, he moves with...",100,min

In [21]:
df['Duration_value'] = pd.to_numeric(df['Duration_value'], errors='coerce')

In [23]:
df['cast_list'] = df['cast'].str.split(", ")

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8807 non-null   str
 1   type            8807 non-null   str
 2   title           8807 non-null   str
 3   director        8807 non-null   str
 4   cast            8807 non-null   str
 5   country         8807 non-null   str
 6   date_added      8807 non-null   datetime64[us]
 7   release_year    8807 non-null   int64
 8   rating          8807 non-null   str
 9   duration        8807 non-null   str
 10  listed_in       8807 non-null   str
 11  description     8807 non-null   str
 12  Duration_value  8807 non-null   int64
 13  Duration_type   8807 non-null   object
 14  cast_list       8807 non-null   object
dtypes: datetime64[us](1), int64(2), object(2), str(10)
memory usage: 1.0+ MB

In [84]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast              0
country           0
date_added        0
release_year      0
rating            0
duration          0
listed_in         0
description       0
Duration_value    0
Duration_type     0
cast_list         0
dtype: int64

In [24]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Duration_value,Duration_type,cast_list
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Availabe,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min,[Not Availabe]
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1,Season,"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab..."
3,s4,TV Show,Jailbirds New Orleans,Unknown,Not Availabe,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",1,Season,[Not Availabe]
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2,Seasons,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ..."

In [86]:
df.to_csv('cleaned_netflix.csv', index=False)